### ISSUE TITLE
Writing a symbol in iodide REPL

### ISSUE THREAD

**Issue by KristofferC** [Keno/julia-wasm#15]
Seems like it is parsed incorrectly.

![capture](https://user-images.githubusercontent.com/1282691/51496867-93f96700-1dc1-11e9-92f3-26c84cbba6eb.PNG)

**Comment by Keno** [comment]
Seems to work for me. Did you do something before that could have corrupted memory?
<img width="875" alt="screen shot 2019-01-22 at 12 32 46 am" src="https://user-images.githubusercontent.com/1291671/51514371-66bab200-1ddd-11e9-85e1-3237eb72fe3a.png">

**Comment by KristofferC** [comment]
I probably didn't realize you need to type it in a cell to the left. I typed it in the `>>` to the right.
