### ISSUE TITLE
Dependencies fail to build with LLVM wasm backend

### ISSUE THREAD

**Issue by Keno** [Keno/julia-wasm#8]
Since for #3 we will likely need to build with the LLVM backend, we should prepare for that. Currently some of our dependencies fail to build (gmp, pcre2) because they have broken configure tests for built-in functions. The action item here is to figure out what the exact issue is and either to fix the configure checks upstream or to patch LLVM to fix this.
```
conftest.c:93:6: warning: incompatible redeclaration of library function 'memset' [-Wincompatible-library-redeclaration]
char memset ();
     ^
conftest.c:93:6: note: 'memset' is a builtin with type 'void *(void *, int, unsigned long)'
1 warning generated.
LLVM ERROR: Prototypeless function used with conflicting signatures: memset
```

**Comment by tshort** [comment]
I tried that a couple of weeks ago and got stuck. I’ll take another look.

**Comment by Keno** [comment]
This works now.
